services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./data/parking-control/db:/var/lib/postgresql/data


